# Detailed Linear Algebra for Data Science

## Introduction
This document provides an in-depth look at the key concepts of linear algebra essential for data science. Each section includes definitions, explanations, and examples relevant to the application in data science.

## Vectors and Spaces

### Definition of Scalers and Vectors

- **Scalars**:  These are quantities that have only magnitude (size or amount) but no direction. Think of them like simple numbers that tell you how much of something there is, but not where it's going. A good example is temperature. If it's 30 degrees Celsius, that number tells you how hot it is, but not in which direction the heat is going. Other examples include things like speed, mass, and time.
- **Vectors**:s: On the other hand, vectors are quantities that have both magnitude and direction. They're like arrows pointing somewhere, with the length of the arrow showing how much there is of something and the direction of the arrow showing where it's going. For example, if you're driving a car, your velocity is a vector. It tells you not just how fast you're going (the speed) but also in which direction. Similarly, force is a vector since it's not enough to know how strong the force is; you also need to know in which direction it is applied.

So, in short, scalars are just simple numbers indicating how much of something there is, while vectors are like arrows that tell you how much there is and in which direction it's going.

- **Scalars vs. Vectors**: Scalars are single numbers, while vectors consist of multiple scalar val
  ues.
- **Vector Operations**:
    - **Addition**: Adding corresponding elements of two vectors.
    - **Subtraction**: Subtracting corresponding elements of two vectors.
    - **Scalar Multiplication**: Multiplying each element of a vector by a scal

### Vector Spaces

Vector spaces, "span" and "basis" are two important concepts that help us understand how vectors work together in a space. Let's break them down in simple terms:
- **Span and Basis**:
    - **Span**: Set of all possible linear combinations of a set of vectors.The span of a set of vectors is all of the vectors you can make by combining those vectors. When you combine vectors, you're doing two things: scaling them (multiplying them by numbers) and adding them together. The span is like a recipe book that tells you all the different dishes (vectors) you can cook up using a specific set of ingredients (the original vectors). If the span of a set of vectors includes every possible vector in the space, then we say that these vectors span the entire space. For example, in a two-dimensional space (like a flat sheet of paper), if you have two non-parallel arrows (vectors), you can reach any point on the paper by stretching, shrinking, and combining these arrows. So, these two arrows span the two-dimensional space.

      
    - **Basis**: The minimum set of linearly independent vectors that span a vector space. A basis of a vector space is a set of vectors that are both linearly independent (none of the vectors can be made by combining the others) and span the entire space. You can think of a basis as the most "efficient" set of ingredients in your recipe book. With these ingredients (vectors), you can make every possible dish (vector in the space) without any leftovers or waste. In our two-dimensional space example, if you have two arrows that are not pointing in the same or opposite directions, they can serve as a basis. You can reach any point on the paper using combinations of these two arrows, and neither arrow is redundant (you can't create one arrow by using the other).
    - In simpler terms, the span tells you what you can reach with your vectors, and the basis is the minimal, non-redundant set of vectors you need to reach everything in the span
      
- **Linear Independence**: A set of vectors is linearly independent if no vector in the set can be written as a linear combination of the others. span.ers.





In [2]:
## Vectors and Spaces

### Python Example: Vector Operations

import numpy as np

# Define two vectors
vector1 = np.array([2, 3])
vector2 = np.array([1, 4])

# Vector addition
addition = vector1 + vector2

# Vector subtraction
subtraction = vector1 - vector2

# Scalar multiplication
scalar_multiplication = 2 * vector1

print("Addition:", addition)
print("Subtraction:", subtraction)
print("Scalar Multiplication:", scalar_multiplication)


Addition: [3 7]
Subtraction: [ 1 -1]
Scalar Multiplication: [4 6]


## Matrix Algebra

### Matrices and Matrix Operations
- **Matrices**: A matrix is a rectangular array of numbers, symbols, or expressions.
- **Matrix Operations**:
    - **Addition/Subtraction**: Element-wise addition or subtraction.
    - **Scalar Multiplication**: Multiplying each element of the matrix by a scalar.
    - **Matrix Multiplication**: Combining rows of the first matrix with columns of the second.

### Types of Matrices
- **Identity Matrix**: A square matrix with 1's along the diagonal and 0's elsewhere.
- **Diagonal Matrix**: A matrix where the entries outside the diagonal are all zero.
- **Symmetric Matrix**: A matrix that is equal to its transpose.

### Matrix Inversion and Determinants
- **Inverse of a Matrix**: A matrix that, when multiplied with the original matrix, yields the identity matrix.
- **Determinant of a Matrix**: A scalar value that represents the volume scaling factor of the linear transformation described by the matrix.
The determinant of a matrix, is a special number that can be calculated from the elements of a square matrix (a matrix with the same number of rows and columns). It has several important interpretations and uses:
    
Volume Scaling Factor: Imagine a shape being transformed in space, like stretching or squishing a cube into a different shape. The determinant tells you how much the volume of that shape changes due to the transformation. A determinant of 1 means the volume stays the same, greater than 1 means the volume increases, and less than 1 means it decreases.    

Matrix Invertibility: The determinant can tell you whether a matrix has an inverse. If the determinant is 0, the matrix cannot be inverted, which in geometric terms means the transformation squashes the shape into a lower-dimensional space (like squishing a 3D shape into a flat 2D shape    ).

Orientation Change: The sign of the determinant (positive or negative) indicates whether the transformation preserves the orientation of the shape. A positive determinant means the orientation is preserved, while a negative determinant means it is reversed (like turning a glove inside out).

In summary, the determinant provides a single value that encapsulates important geometric properties of a matrix, particularly in relation to transformations it represents.


In [3]:
import numpy as np

# Define two matrices
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

# Matrix addition
addition = matrix1 + matrix2

# Matrix multiplication
multiplication = np.dot(matrix1, matrix2)

print("Matrix Addition:\n", addition)
print("Matrix Multiplication:\n", multiplication)


Matrix Addition:
 [[ 6  8]
 [10 12]]
Matrix Multiplication:
 [[19 22]
 [43 50]]


In [5]:
import numpy as np

# 1. Identity Matrix (3x3)
identity_matrix = np.eye(3)
print("Identity Matrix (3x3):\n", identity_matrix)

# 2. Diagonal Matrix
diagonal_matrix = np.diag([1, 2, 3])
print("\nDiagonal Matrix:\n", diagonal_matrix)

# 3. Symmetric Matrix
symmetric_matrix = np.array([[1, 2, 3],
                             [2, 4, 5],
                             [3, 5, 6]])
print("\nSymmetric Matrix:\n", symmetric_matrix)

# Matrix for inversion and determinant (must be square and non-singular)
matrix_for_inversion_and_determinant = np.array([[4, 7],
                                                 [2, 6]])

# 4. Inverse of a Matrix
inverse_matrix = np.linalg.inv(matrix_for_inversion_and_determinant)
print("\nInverse of a Matrix:\n", inverse_matrix)

# 5. Determinant of a Matrix
determinant = np.linalg.det(matrix_for_inversion_and_determinant)
print("\nDeterminant of a Matrix:", determinant)


Identity Matrix (3x3):
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Diagonal Matrix:
 [[1 0 0]
 [0 2 0]
 [0 0 3]]

Symmetric Matrix:
 [[1 2 3]
 [2 4 5]
 [3 5 6]]

Inverse of a Matrix:
 [[ 0.6 -0.7]
 [-0.2  0.4]]

Determinant of a Matrix: 10.000000000000002


Calculating the determinant of a matrix is a fundamental operation in linear algebra. The method varies depending on the size of the matrix. Here's a general guide for calculating the determinant:

**2x2 Matrix**
For a 2x2 matrix, the determinant is calculated as follows:

Given a matrix:

( a  b

  c  d )

The determinant is:
det = ad−bc

**3x3 Matrix**

For a 3x3 matrix, the calculation is slightly more complex. The determinant is calculated by expanding along a row or a column (here, I'll use the first row for simplicity):

Given a matrix:

( a b c

 d e f
 
 g h i )

det=a(ei−fh)−b(di−fg)+c(dh−eg)

This method involves finding the determinants of three 2x2 matrices and combining them.

The determinant of the given matrix 

1
 
4
 3

 

 

1
is 
−
2.0
−2.0.

Here's what this determinant tells us:

Volume Change: The absolute value of the determinant (2.0) indicates how much the area (since it's a 2x2 matrix) is scaled when a geometric transformation represented by this matrix is applied. In this case, any area would be scaled by a factor of 2.

Invertibility: Since the determinant is not zero, this matrix is invertible. It means there exists another matrix which, when multiplied with this one, will give the identity matrix.

Orientation: The negative sign of the determinant (-2.0) is significant. It indicates that the transformation would reverse the orientation of the space. For instance, if this matrix were used to transform a shape in 2D space, the shape would be flipped over, like turning a piece of paper over to its other side.

So, the determinant gives us valuable information about how the matrix transforms space, including scaling, invertibility, and orientation changes.

## Eigenvalues and Eigenvectors

### Introduction to Eigenvalues and Eigenvectors
- **Definition**: 
Eigenvalues and eigenvectors are concepts from linear algebra that have broad applications in fields like engineering, physics, and data analysis. Let's break them down into layman's terms:

- **Eigenvectors**:  Non-zero vectors that change at most by a scalar factor when that linear transformation is applied.Imagine you have a transformation machine that changes the shape or direction of objects. You put in a vector (think of it as an arrow pointing in a certain direction), and the machine transforms it. Now, most vectors will come out of this machine pointing in a different direction. However, there might be some special vectors (eigenvectors) that come out still pointing in their original direction, though their length might have changed. These special vectors are called eigenvectors of the transformation.

- **Eigenvalues**:Scalars that measure the factor by which the eigenvector is scaled during a linear transformation.The eigenvalue is a number associated with each eigenvector. It tells you how much the length of the eigenvector changes when it goes through the transformation. If the eigenvalue is 2, for example, the eigenvector becomes twice as long. If it's 0.5, the eigenvector becomes half as long. If the eigenvalue is 1, the eigenvector doesn't change in length at all.

In simpler terms, in the world of transformations, eigenvectors are the vectors that manage to keep their direction, and eigenvalues tell us how their length is altered. They are important because they reveal the fundamental properties of the transformation, such as which directions are stretched or shrunk and by how much.

### Calculating Eigenvalues and Eigenvectors
- **Characteristic Polynomial**: A polynomial which is derived from the determinant of a matrix and is used to find eigenvalues.
- **Applications in Dimensionality Reduction (PCA)**:
    - Principal Component Analysis (PCA) uses eigenvalues and eigenvectors to reduce the dimensionality of data sets, improving the interpretability while minimizing information loss.


In [6]:
import numpy as np

# Define a matrix
matrix = np.array([[4, 2], [1, 3]])

# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)

print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)


Eigenvalues: [5. 2.]
Eigenvectors:
 [[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]



## Singular Value Decomposition

### Understanding SVD
- **Concept and Mathematical Formulation**: 
    - Decomposition of a matrix into three other matrices. It provides a way of diagonalizing a matrix.
    - Equation: `A = UΣV*` where A is the original matrix, U and V are orthogonal matrices, and Σ is a diagonal matrix of singular values.

### Applications of SVD in Data Science
- **Data Compression**: Reducing the size of data by eliminating redundant features.
- **Noise Reduction**: Improving the quality of data by removing noise.

## Applications in Data Science

### Linear Algebra in Machine Learning
- **Feature Spaces**: Using vector spaces to represent features in machine learning models.
- **Linear Regression, PCA, and Other Algorithms**: 
    - Linear regression involves matrix operations for predicting outcomes.
    - PCA for dimensionality reduction.
    - Other algorithms where linear algebra is pivotal.

### Network Analysis
- **Adjacency Matrices**: Representing graphs and networks using matrices.
- **Graph Theory Concepts**: Understanding the structure and properties of networks.

## Conclusion
- Recap of the importance of linear algebra in data science.
- Discussion on how these concepts are integral to understanding data and building predictive models.

## References
- [Linear Algebra and Its Applications, David C. Lay]
- [Introduction to Applied Linear Algebra – Vectors, Matrices, and Least Squares, Stephen Boyd and Lieven Vandenberghe]
- [Online resources and courses for further study.]

